version: "3.4"

services:
  app:
    container_name: node-mongo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

networks:
  default:
    external: true
    name: bike

volumes:
  data:
