version: "3.4"

services:
  app:
    container_name: node-mongo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    external: true
    name: bike
