GET http://localhost:5000/riders/paul/ridenotes

###

PATCH http://localhost:5000/riders/paul/ridenotes
Content-Type: application/json

{
    "rideName": "ride 2",
    "notes": "gooooooood",
    "weather": "sunny",
    "weight": "160",
    "restingBP": "60"
}