GET http://localhost:5000/riders

###

DELETE http://localhost:5000/riders/60807221c529202776977627


###
 
POST http://localhost:5000/riders/bob/trainingplans
Content-Type: application/json

{
    "planName": "plan a"
}

###

DELETE http://localhost:5000/trainingplans/607f3de887dddba25bd96258

###

GET http://localhost:5000/trainingplans/60b2a5cf526e194729c97790
